### ISSUE TITLE
Got Unexpected token function

### ISSUE THREAD

**Issue by ferolmo** [faviator/faviator#1]
Hi, i just installed faviator like this `npm install -g faviator` and all goes right, but when i try to run `faviator -h` i got this error:

```
async function main(options) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Wanted to use it to generate a new icon for my web but.. cant do it :(

**Comment by ycmjason** [comment]
May I know which node version you are running this on?

**Comment by Fdom92** [comment]
Sure! Im using right now 6.9.1

**Comment by ycmjason** [comment]
Currently faviator supports only node >=8. 

I would recommend using [n](https://github.com/tj/n) or [nvm](https://github.com/creationix/nvm) to switch between node versions.

**Comment by ycmjason** [comment]
I would like to provide more support if you encounter any more issue.

**Comment by Fdom92** [comment]
Oh.. im using nvm so will do it, thanks for this fast answer! :) and cool tool 

_tried with 8.3.0 and worked as expected big thanks_

**Comment by ycmjason** [comment]
I am really glad to hear this! I will consider adding support for more versions of node. Maybe compiling to ES5 with babel... But this wouldn't be my priority right now.

In case you haven't already know, you can go to the [playground](https://www.faviator.xyz/playground) and test our the configs.
