### ISSUE TITLE
Vertical position is off

### ISSUE THREAD

**Issue by cfjedimaster** [faviator/faviator#4]
While using the playground, I noticed that the initial position of the text was a bit high. I thought that it was a bit odd for the *default* to not be vertically centered, but I just lowered it till it looked ok:

![image](https://user-images.githubusercontent.com/393660/36734165-4dfaed90-1b98-11e8-9877-50078ca7a1d9.png)

When I used the output:

```
faviator --size '230' --text 'RC' --dx '-2.5' --dy '20.5' --font-size '70' --font-family 'Dancing Script' --font-color '#ffffff' --background-color '#ff0000' --border-width '3.5' --border-color '#feeeec' --border-radius '50'
```

and generated a PNG, it was too low:

![image](https://user-images.githubusercontent.com/393660/36734191-5e618374-1b98-11e8-99bd-ae8b2bee10e9.png)

**Comment by ycmjason** [comment]
Can I recommend refresh and do your design again?

On my machine, with your settings, the icon showing seem to be the same as the one that is generated.

![](https://i.imgur.com/4vY5VA6.png)

I know it might be hard to replicate the exact design given a config. I have marked this down and will make this easier in the next improvement release of the playground.

**Comment by cfjedimaster** [comment]
On a fresh load, changing nothing, it is definitely not aligned right (Firefox, Windows):

![image](https://user-images.githubusercontent.com/393660/36736788-0c9435f8-1b9f-11e8-8207-96b48cb29543.png)

**Comment by ycmjason** [comment]
Thank you very much for reporting this issue. Looks like there is an issue of how firefox generates the svg. I will look into this tonight. Meanwhile can you use Google Chrome for now and see if there is any issue?

**Comment by cfjedimaster** [comment]
Looks just fine in Chrome.

**Comment by ycmjason** [comment]
I found the issue. Apparently firefox is not respecting `aligment-baseline` on `<text>` node properly, I will change it to `dominant-baseline` instead and should fix the issue. I will push a fix tonight.

Thanks for letting me know! :smiley:

**Comment by cfjedimaster** [comment]
No worries - thanks for the cool tool.

**Comment by ycmjason** [comment]
@cfjedimaster I have pushed a patch for the playground. It should work fine now on firefox.

It is a bit funny that firefox doesn't work as what themselves have documented on MDN.

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline
