### ISSUE TITLE
Add functionality for random font selection

### ISSUE THREAD

**Issue by ameykusurkar** [faviator/faviator#5]
There are too many fonts provided by Google, it is impractical to look through all of them to try new ones. I suggest adding a button that picks a random font, so that users can try out new fonts.

**Comment by ycmjason** [comment]
This issue was moved to faviator/faviator.xyz#7

**Comment by ycmjason** [comment]
@ameykusurkar feature added

see https://github.com/faviator/faviator.xyz/issues/7
